trigger: none

resources:
  pipelines:

  - pipeline: g2core
    source: ZiathLtd.g2-core
    trigger: none

  - pipeline: firmware
    source: ZiathLtd.reader-g2-firmware
    trigger: none

jobs:
- job: BuildPiImage

  displayName: Build Pi Image

  pool:
    name: Default
    demands:
      - Agent.OS -equals Linux
      - Agent.Name -equals bookworm-agent

  steps:

  - checkout: self
    clean: true

  #
  # Download selected pipeline artifacts
  #
  - download: g2core
    artifact: DEBIAN

  - download: firmware
    artifact: DEBIAN

  #
  # Verify what was downloaded
  #
  - script: |
      echo "Pipeline workspace:"
      find $(Pipeline.Workspace) -type f
    displayName: Show Downloaded Files

  #
  # Copy DEBs into pi-gen
  #
  - script: |

      mkdir -p stage2/04-firstboot/files

      find $(Pipeline.Workspace)/g2core -name "*.deb" -exec cp -v {} stage2/04-firstboot/files/ \;

      find $(Pipeline.Workspace)/firmware -name "*.deb" -exec cp -v {} stage2/04-firstboot/files/ \;

      echo ""
      echo "Files in stage2/04-firstboot/files:"
      ls -lh stage2/04-firstboot/files

    displayName: Copy DEBs Into Pi-Gen

  #
  # Build image
  #
  - script: |

      chmod +x build.sh

      sudo ./build.sh

    displayName: Build Image

  #
  # Verify image
  #
  - script: |
      echo "Generated images:"
      find deploy -type f
    displayName: Verify Image

  #
  # Publish image
  #
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: deploy
      artifact: IMAGE
    displayName: Publish Image
